---
version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
      time: '02:00'
      timezone: Europe/Amsterdam
    labels:
      - dependencies
    target-branch: main
    assignees:
        - "bsmeding"
