name: Sync NetBox Device Types (all vendors)

on:
  schedule:
    - cron: '0 0 * * *'   # daily 00:00 UTC
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add upstream (NetBox)
        run: |
          git remote add upstream https://github.com/netbox-community/devicetype-library
          git fetch upstream master

      - name: Sync folders from upstream/master
        run: |
          git checkout upstream/master -- device-types elevation-images module-images module-types rack-types

      - name: Lint YAML (optional)
        run: |
          pipx install yamllint
          yamllint -s device-types

      - name: Create PR if changes
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(sync): update from netbox-community/devicetype-library (master)"
          title: "Sync: NetBox devicetype-library (master)"
          branch: chore/sync-netbox
          body: "Automated sync of device-types, elevation-images, module-images, module-types, rack-types."
