########################################
#
#  Sync with the upstream Nautobot device_type repository to get latest changes 
#
########################################

name: Sync Upstream Subfolder

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your forked repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/nautobot/devicetype-library
          git fetch upstream main

      - name: Sync device-types, elevation-images, module-images, and module-types from upstream
        run: |
          # Create a temporary folder to hold the upstream files
          mkdir -p temp_sync

          # Sync the device-types folder
          git checkout upstream/main -- device-types
          rsync -av --delete device-types temp_sync/
          
          # Sync the elevation-images folder
          git checkout upstream/main -- elevation-images
          rsync -av --delete elevation-images temp_sync/

          # Sync the module-images folder
          git checkout upstream/main -- module-images
          rsync -av --delete module-images temp_sync/

          # Sync the module-types folder
          git checkout upstream/main -- module-types
          rsync -av --delete module-types temp_sync/

          # Move the synced folders back to the root
          mv temp_sync/device-types ./device-types
          mv temp_sync/elevation-images ./elevation-images
          mv temp_sync/module-images ./module-images
          mv temp_sync/module-types ./module-types

      - name: Commit changes if any
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add device-types elevation-images module-images module-types
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Sync folders from upstream"
            git push
          fi
