name: Sync NetBox Device Types

on:
  schedule:
    - cron: '0 0 * * *'   # daily at 00:00 UTC
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add upstream NetBox
        run: |
          git remote add upstream https://github.com/netbox-community/devicetype-library || true
          git fetch upstream master

      - name: Sync folders from upstream (add only, do not overwrite)
        run: |
          mkdir -p temp_sync

          git checkout upstream/master -- device-types elevation-images module-images module-types rack-types

          rsync -av --ignore-existing device-types/      temp_sync/device-types/
          rsync -av --ignore-existing elevation-images/  temp_sync/elevation-images/
          rsync -av --ignore-existing module-images/     temp_sync/module-images/
          rsync -av --ignore-existing module-types/      temp_sync/module-types/
          rsync -av --ignore-existing rack-types/        temp_sync/rack-types/

          rsync -av --ignore-existing temp_sync/device-types/      ./device-types/
          rsync -av --ignore-existing temp_sync/elevation-images/  ./elevation-images/
          rsync -av --ignore-existing temp_sync/module-images/     ./module-images/
          rsync -av --ignore-existing temp_sync/module-types/      ./module-types/
          rsync -av --ignore-existing temp_sync/rack-types/        ./rack-types/

          rm -rf temp_sync

      - name: Commit changes if any
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add device-types elevation-images module-images module-types rack-types
          if git diff --cached --quiet; then
            echo "No new upstream files to commit"
          else
            git commit -m "Sync new files from netbox-community/devicetype-library"
            git push
          fi
